-- Постобработка: разбор raw.vacancy_details.payload в широкую таблицу raw.vacancy_details_wide.
-- Отсутствующие поля дают NULL.
INSERT INTO raw.vacancy_details_wide (
    id, name,
    area_id, area_name, area_url,
    type_id, type_name,
    salary_from, salary_to, salary_currency, salary_gross,
    address_raw, address_city, address_street, address_building, address_lat, address_lng,
    address_metro_station_name,
    employer_id, employer_name, employer_url, employer_logo_240,
    schedule_id, schedule_name,
    employment_id, employment_name,
    experience_id, experience_name,
    published_at, created_at, initial_created_at,
    alternate_url, description, key_skills,
    premium, archived, has_test,
    billing_type_id, billing_type_name,
    employment_form_id, employment_form_name,
    work_schedule_by_days, working_hours, professional_roles,
    response_letter_required,
    updated_at
)
SELECT
    d.id,
    d.payload->>'name',
    d.payload->'area'->>'id',
    d.payload->'area'->>'name',
    d.payload->'area'->>'url',
    d.payload->'type'->>'id',
    d.payload->'type'->>'name',
    (d.payload->'salary'->>'from')::numeric,
    (d.payload->'salary'->>'to')::numeric,
    d.payload->'salary'->>'currency',
    (d.payload->'salary'->>'gross')::boolean,
    d.payload->'address'->>'raw',
    d.payload->'address'->>'city',
    d.payload->'address'->>'street',
    d.payload->'address'->>'building',
    (d.payload->'address'->>'lat')::numeric,
    (d.payload->'address'->>'lng')::numeric,
    COALESCE(
        d.payload->'address'->'metro'->>'station_name',
        d.payload->'address'->'metro_stations'->0->>'station_name'
    ),
    d.payload->'employer'->>'id',
    d.payload->'employer'->>'name',
    d.payload->'employer'->>'url',
    d.payload->'employer'->'logo_urls'->>'240',
    d.payload->'schedule'->>'id',
    d.payload->'schedule'->>'name',
    d.payload->'employment'->>'id',
    d.payload->'employment'->>'name',
    d.payload->'experience'->>'id',
    d.payload->'experience'->>'name',
    (d.payload->>'published_at')::timestamptz,
    (d.payload->>'created_at')::timestamptz,
    (d.payload->>'initial_created_at')::timestamptz,
    d.payload->>'alternate_url',
    d.payload->>'description',
    d.payload->'key_skills',
    (d.payload->>'premium')::boolean,
    (d.payload->>'archived')::boolean,
    (d.payload->>'has_test')::boolean,
    d.payload->'billing_type'->>'id',
    d.payload->'billing_type'->>'name',
    d.payload->'employment_form'->>'id',
    d.payload->'employment_form'->>'name',
    d.payload->'work_schedule_by_days',
    d.payload->'working_hours',
    d.payload->'professional_roles',
    (d.payload->>'response_letter_required')::boolean,
    now()
FROM raw.vacancy_details d
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    area_id = EXCLUDED.area_id,
    area_name = EXCLUDED.area_name,
    area_url = EXCLUDED.area_url,
    type_id = EXCLUDED.type_id,
    type_name = EXCLUDED.type_name,
    salary_from = EXCLUDED.salary_from,
    salary_to = EXCLUDED.salary_to,
    salary_currency = EXCLUDED.salary_currency,
    salary_gross = EXCLUDED.salary_gross,
    address_raw = EXCLUDED.address_raw,
    address_city = EXCLUDED.address_city,
    address_street = EXCLUDED.address_street,
    address_building = EXCLUDED.address_building,
    address_lat = EXCLUDED.address_lat,
    address_lng = EXCLUDED.address_lng,
    address_metro_station_name = EXCLUDED.address_metro_station_name,
    employer_id = EXCLUDED.employer_id,
    employer_name = EXCLUDED.employer_name,
    employer_url = EXCLUDED.employer_url,
    employer_logo_240 = EXCLUDED.employer_logo_240,
    schedule_id = EXCLUDED.schedule_id,
    schedule_name = EXCLUDED.schedule_name,
    employment_id = EXCLUDED.employment_id,
    employment_name = EXCLUDED.employment_name,
    experience_id = EXCLUDED.experience_id,
    experience_name = EXCLUDED.experience_name,
    published_at = EXCLUDED.published_at,
    created_at = EXCLUDED.created_at,
    initial_created_at = EXCLUDED.initial_created_at,
    alternate_url = EXCLUDED.alternate_url,
    description = EXCLUDED.description,
    key_skills = EXCLUDED.key_skills,
    premium = EXCLUDED.premium,
    archived = EXCLUDED.archived,
    has_test = EXCLUDED.has_test,
    billing_type_id = EXCLUDED.billing_type_id,
    billing_type_name = EXCLUDED.billing_type_name,
    employment_form_id = EXCLUDED.employment_form_id,
    employment_form_name = EXCLUDED.employment_form_name,
    work_schedule_by_days = EXCLUDED.work_schedule_by_days,
    working_hours = EXCLUDED.working_hours,
    professional_roles = EXCLUDED.professional_roles,
    response_letter_required = EXCLUDED.response_letter_required,
    updated_at = EXCLUDED.updated_at;
