-- Широкая таблица: разобранные поля из raw.vacancy_details.payload (JSON).
-- Отсутствующие в JSON поля остаются NULL.
CREATE TABLE IF NOT EXISTS raw.vacancy_details_wide (
    id                          TEXT PRIMARY KEY,
    name                        TEXT,
    area_id                     TEXT,
    area_name                   TEXT,
    area_url                    TEXT,
    type_id                     TEXT,
    type_name                   TEXT,
    salary_from                 NUMERIC,
    salary_to                   NUMERIC,
    salary_currency            TEXT,
    salary_gross                BOOLEAN,
    address_raw                 TEXT,
    address_city                TEXT,
    address_street              TEXT,
    address_building            TEXT,
    address_lat                 NUMERIC,
    address_lng                 NUMERIC,
    address_metro_station_name  TEXT,
    employer_id                 TEXT,
    employer_name               TEXT,
    employer_url                TEXT,
    employer_logo_240           TEXT,
    schedule_id                 TEXT,
    schedule_name               TEXT,
    employment_id               TEXT,
    employment_name             TEXT,
    experience_id               TEXT,
    experience_name             TEXT,
    published_at                TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ,
    initial_created_at         TIMESTAMPTZ,
    alternate_url               TEXT,
    description                 TEXT,
    key_skills                  JSONB,
    premium                     BOOLEAN,
    archived                    BOOLEAN,
    has_test                    BOOLEAN,
    billing_type_id             TEXT,
    billing_type_name           TEXT,
    employment_form_id          TEXT,
    employment_form_name        TEXT,
    work_schedule_by_days       JSONB,
    working_hours                JSONB,
    professional_roles          JSONB,
    response_letter_required    BOOLEAN,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE raw.vacancy_details_wide IS 'Постобработка raw.vacancy_details: широкий разбор payload (JSON) в колонки';
